name: card100game
description: "Card 100 Game Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_database: ^10.5.7

  # Google Sign In
  google_sign_in: ^6.3.0

  # Facebook Login
  flutter_facebook_auth: ^7.2.0

  # Ads
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
