- name: Locate pubspec.yaml and Build
        run: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1)
          if [ -z "$PUBSPEC_PATH" ]; then
            echo "Error: pubspec.yaml nahi mila!"
            exit 1
          fi
          PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
          echo "Project directory: $PROJECT_DIR"
          
          cd "$PROJECT_DIR"
          flutter pub get
          flutter build apk --release --android-skip-build-dependency-validation
