name: Flutter Build APK

on:
  push:
    branches:
      - main
      - master
      - Perfect-Game
      - restored-game
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Locate pubspec.yaml and Prepare Environment
        id: prep
        run: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1)
          if [ -z "$PUBSPEC_PATH" ]; then
            echo "Error: pubspec.yaml nahi mila!"
            exit 1
          fi
          PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Decode Keystore
        run: |
          mkdir -p ${{ env.PROJECT_DIR }}/android/app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '\r\n' | base64 -d > ${{ env.PROJECT_DIR }}/android/app/release.jks

      - name: Generate Icons and Build Release APK
        run: |
          cd ${{ env.PROJECT_DIR }}
          flutter pub get
          dart run flutter_launcher_icons || true
          flutter build apk --release --android-skip-build-dependency-validation
        env:
          KEYSTORE_PATH: "release.jks"
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: '**/build/app/outputs/flutter-apk/app-release.apk'
